---
Name: IanSimpson
After: framework/routes#coreroutes
---
Silverstripe\Control\Director:
  rules:
    'oauth': IanSimpson\OAuth2\OauthServerController
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - IanSimpson\OAuth2\Admin\ClientAdmin
    - IanSimpson\OAuth2\Admin\ScopeAdmin
    - IanSimpson\OAuth2\Admin\AccessTokenAdmin
SilverStripe\Core\Injector\Injector:
  IanSimpson\OAuth2\Logger:
    factory: 'IanSimpson\OAuth2\LogFactory'
